version: "3.0"
services:
  redis:
    image: "redis:alpine"
    # The Command will make redis-server run with our custom Configuration
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data #Used for persisting data
      - ./redis/conf:/usr/local/etc/redis #Used for configuring redis
    networks:
      - data_sharing
  api:
    # Makes the compose- build our Image based on the files in api folder
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - data_sharing
    restart: on-failure
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - redis
      - api
    networks:
      - data_sharing

networks:
  data_sharing:
    driver: bridge